---
- hosts: localhost
  gather_facts: no

  tasks:
  - name: listdevices
    uri:
      url: https://api.equinix.com/metal/v1/projects/a2508413-620f-41e5-9caa-42b5fb000edd/devices
      method: POST
      body_format: json
      validate_certs: no
      headers:
        X-Auth-Token: "{{ api_key }}"
      body: "{{ lookup('file','create_metal_web.json') }}"
      status_code: 201
    register: create_devices
    
  - name: printdevices
    ansible.builtin.debug: 
      var: create_devices
      
     
