---
- hosts: localhost
  gather_facts: no

  tasks:
  - name: listdevices
    uri:
      url: https://api.equinix.com/metal/v1/projects/a2508413-620f-41e5-9caa-42b5fb000edd/devices
      method: GET
      #body_format: json
      validate_certs: no
      headers:
        X-Auth-Token: "{{ api_key }}"
      #body:
      #- [ name, your_username ]
      #- [ password, your_password ]
      #- [ enter, Sign in ]
      status_code: 200
    register: devices
    
  - name: save the json as variable
    set_fact: 
      jsondata: "{{ result.stdout | from_json }}"
  
  - name: devicenames
    set_fact: 
      devicenames: "{{ jsondata | json_query(jmesquery) }}"
    vars:
      jmesquery: '*.devices[*].hostname'
   
    - name: deviceid
    set_fact: 
      deviceid: "{{ jsondata | json_query(jmesquery) }}"
    vars:
      jmesquery: *.devices[*].id'
     
    - name: print the list
    debug:
      msg: " "{{ item1 }}" = "{{ item2 }}" "
      with_items:
      - "{{ devicenames }}"
      - "{{ deviceid }}"


